name: Build and Package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: lazisna-build
          path: dist/
